server:
  port: 8000
  servlet:
    context-path: /games
  tomcat:
    uri-encoding: UTF-8

#默认的位置是src/main/webapp 这里可以更换，比如/pages/ 那么目录就变成了src/main/webapp/pages


spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  thymeleaf:
    cache: false
  datasource:
    name: games
    url: jdbc:mysql://106.13.47.126:3306/games?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: x5zrqj@RZWD
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.sport.games.entity

image:
  path: D://var/games/
#  path: //var/games/
